name: my-project
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy-to-ecs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    # - name: install modules
    #   run: npm i
    - name: Build
      run: npm run build
    - name: deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:  
        username: 'root'
        server: ${{ secrets.HOST_NAME }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './build/*'
        remote_path: '/usr/share/nginx/react-front'
        args: '-o ConnectTimeout=5'
    - name: reload
      run: sudo nginx -c /etc/nginx/nginx.conf
      run: nginx -s reload

