name: my-project
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: install modules
      run: npm i
    - name: Build
      run: npm run build
# 利用action把build好的文件上传到服务器/var/www/react-app路径下,需要确认此目录已在服务端创建
    - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'root'   #ssh user name
          server: '${{ secrets.SERVER_IP }}' #引用之前创建好的secret
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} #引用之前创建好的secret
          local_path: './build/*'  # 对应我们项目build的文件夹路径
          remote_path: '/usr/share/nginx/dist'
    - name: reload nginx
      run: nginx -s reload

    # - name: Build and Deploy
    #   uses: JamesIves/github-pages-deploy-action@master
    #   env:
    #     ACCESS_TOKEN: ${{ secrets.self_page }}
    #     BRANCH: main
    #     FOLDER: build
    #     BUILD_SCRIPT: npm install && npm run build